---
title: Natural cubic spline for Non-parametric regression
author: Jiaming Shen
date: '2018-02-19'
slug: nonparametric-regression
categories:
  - Statistics
tags:
  - regression
  - nonparametric
  - smoothin
---

Here is the a new note about the non-parametric regression.

Quote from the Green and Silverman(1994),1.2.2, there are many ways to quantify the roughness of a curve, which is means the how 'rough' or 'wiggly' the curve $g$ is. An intuitively way is $\int _a ^b \{g''(t)\}^2dt$,the integrated squared second derivative.

The general form of penalized least squares regression
$$S(g)=\sum^n_{i=1}\{Y_i-g(t_i)\}^2+a\int^b_a\{g''(x)^2\}dx$$
So the fit is not only concern about the goodness of fit(if so,1-NN is the best method among all methods for the data set), but also consider about the roughness.
$\alpha$ is 'rate of exchange', or weight of penalty. Minimizing $S(g)$ is the best compromise between smoothness and goodness-of-fit for a given $\alpha$.
$\alpha$ is large->more weighted on smoothness,$\hat g$ would be  curvature. $\alpha$ -> 0, the $\alpha$ is relative small,then the square sum would be the main contribution to $S(g)$, $\hat g$ will approach the interpolating curve.



Semiparametric model
$$
Y=g(t)+x^T\beta+error
$$

***

Following is review and notes for Green and B.W. Silverman(1994),Nonparametric Regression and Generalized Linear Models: A roughness penalty approach. The paragraph upon actually from the chap1 but only some main ideas.

### Chapter 2. Interpolating & smoothing splines.

Main goal: How to find a curve g to minimize $S(g)$.

A pivotal role: cubic splines.

Some basic notations:

$t_1,...t_n$ is knots in $[a,b]$ with $a<t_1<...<t_n<b$.

The cubic spline g is

- cubic polynomial in $(a,t_1),(t_1,t_2),....,(t_n.b)$
- The polynomial pieces fit together at the points $t_i$. ($g,g',g''$ agrees at $t_i$).

There are many equivalent ways of specifying a cubic spline. One is
$$
g(t)=d_i(t-t_i)^3+c_i(t-t_i)^2+b_i(t-t_i)+a_i,\ for\ t_i\leq t \leq t_{i+1}
$$
for given constant $a_i,b_i,c_i,d_i,i=0,...,n$,define $t_0=a,t_{i+1}=b $;
This is the intuitive about the "piecewise cubic polynomial". 

Definition: Natural cubic spline(NCS):

-  Its second and third derivatives are zero at a and b.

This condition called natural boundary conditions.

Imply $d_0=c_0=d_n=c_n=0$-> g is linear on $[a,t_1],[t_n,b]$.

> ~~Comment~~:(Failed)
>
- ~~It contains 4(n+2) parameters. As the cubic spline definition, the "$g,g',g''$ agrees at $t_i$.",will have 3(n+1) constrains.The nature spline will add 4 constrains. For interpolating problem, interpolate means $g(t_i)=z_i$ than another n+2 constrains.Then totally it is 4n+9 constrains. Is the solution always exist?~~ 
Maybe I should find the answer from Tibshirani and Hastie(2004), because the way I thought is from it.
>
- ~~Deep thinking: g agrees at $t_i$ is the same as $g(t_i)=z_i$ condition? than there are less n constrains.It is only 3n+8 constrains.~~ 
>
- Is the choosing knots the same as interpolating the known knots? (It should be same I think.)

***

##### 2.2.1 The value-second derivative representation
This is another way to representation NCS, by its value and its second derivative at each knots.

Notation:

$$
g_i=g(t_i)\ and\ \gamma_i=g''(t_i)\ for\ i=1,...,n
$$
$\mathbf{g}=(g_1,...,g_n)^T,\mathbf{\gamma}=(\gamma_1,...,\gamma_n)^T$. Author assert $\mathbf{g},\mathbf{\gamma}$ specify the g completely.

>~~comment:(Failed)~~
>
- ~~As the comment before, if it only contains 3n+6 constrains, then give extra information in $g''$, it would have extra n constrains,than totally 4n+8 constrains. Than if it has solution, it should be unique.~~
>
- ~~Back to begging for count: n+2 constrains for value $z_i$,4 nature boundary conditions,n constrains for $g''$,n constrains for agree $g$, not meet the 4n+8 parameters.~~
>
- ~~Think in a nother way, the linear system. We have n+2 cubic polynomials, each polynomials have 4 parameters. Two value of polynomials, the tail and the head: two constrains. The tail and head 2-derivatives: two constrains. Tail and head 1-derivatives: agree or 0: another 2 constrains. Then there are 6 constrains for 4 parameters.Ofc some a degenerate, but how to count in this way?~~ 
>
- Refer to ESL again.

The neccesaary and sufficient condition for the vectors genuinely to represent a natural cubic spline on the given knot sequence.

Definition:

$h_i=t_{i+1}-t_i$, Q is $n\times (n-2)$ band matrices with entries as
$$
q_{j-1,j}=h^{-1}_{j-1},q_{jj}=-h^{-1}_{j-1}-h^{-1}_{j}, q_{j+1}=h^{-1}_j
$$
others are zero, $q_{ij}=0,if\ |i-j|\geq2$,$i=1,...,n.j=2,...,n-1$.
Band matrices R is $(n-2)\times(n-2)$,given by
$$
r_ii=\frac{1}{3} (h_{i-1}+h_i)\\
r_{i,i+1}=r_{i+1,i}=\frac{1}{6}h_i.
$$
$i=2,...,n-1$,$r_{ij}=0\ for\ |i-j|\geq2. $

Property: R is strictly diagonal dominant: $|r_{ii}|>\sum_{i\neq j}|r_{ij}|$. R is strictly positive-definite.
btw: Q is three-wide 
Define:
$$K=QR^{-1}Q^T$$
Then we have the theorem:

Theorem:

$\mathbf{g}$ and $\mathbf{\gamma}$ specify a natural cubic spline iff $Q^T\mathbf{g}=R\gamma$.
Then the roughness penalty will satisfy $\int ^b_a g''(t)dt=\gamma^TR\gamma=\mathbf{g}^TK\mathbf{g}$

##### 2.2 Interpolating spline
Goal: Main part in smoothing, but interpolating can simplify and clarify subsequent discussion of the smoothing problem.

Interpolating :$z_1,...,z_2 \rightarrow t_1,...t_n$. We have $g(t_i)=z_i$.

Approach: 

- Just straight line.
- Smoothing curve.

Of course the straight line if not fit what we want, we than discussing about the smoothing curve.

Then the workflow in below is

1. Define the "Smooth"
2. Goal: Smoothest
3. NCS is smoothest.

Why do this: 

The smoothing curve for interpolating is not unique, in this way, we want to find the best one among all the potential curves.
If we want the best one, we need define what the meaning of best, then we need define "Smooth".

First, we define the working space as all the function with two continuous derivatives in domain $[a,b]$, called $S[a,b]$. Then we need to find which one is best in $S[a,b]$.
Back to the beginning of this document, the intuitively definition of smoothness is $\int _a ^b g''$.

A result showed that natural cubic spline interpolating minimums the $\int _a ^b g''$. 

The next questions is

- why NCS is smoothest?
- Is the NCS interpolating unique?
- How to calculate? 

Let's ask the second question first.

Theorem:

Suppose $n\geq 2$ and that $t_1<...<t_n$ with given $z_1,...,z_n$, there is a unique natural cubic spine $g$ with knots at the point $t_i$ satisfying $g(t_i)=z_i$ for $i=1,...,n$.

proof:

By theorem before, the sufficient and neccessary condition for $\mathbf{g},\gamma$ specify a NCS. Then the condition specify $\mathbf{g}$, the free parameter is $\gamma$, so if there exist a unique $\gamma$ to meet the condition, then proofed.
Since $\mathbf{R}$ is strictly positive-definite, there will be aunique $\gamma=R^{-1}Q^T\mathbf{g}$.QED.

The key thing is the previous theorem, but idk yet how to prove that.

Computation discussion:

Then let us ask the third question, how to calculate.

As the R is band matrix with width of band is 2,a triagonal matrix, we do not need to calculate the $R^{-1}$, there is a fast and iteravie algorithm to get the answer with O(n). There are also special structure for Q, we also do not need to calculate $Q^T\mathbf{g}$ in the matrix manipulate way, we have 
$$
(Q^T\mathbf{g})_i=\frac{g_{i+1}-g_{i}}{h_i}-\frac{g_i-g_{i-1}}{h_{i-1}}
$$
which is also O(n).

Algorithm:

- **STEP 1** Set $g_i=z_i$ for i=1,...,n.
- **STEP 2** Set $\mathbf{x}=Q^T\mathbf{g}$ and solve $R\gamma=\mathbf{x}$ for $\gamma$.

##### 2.2.2 Optimality properties of the natural cubic spline interpolant

This section solves the question 1, Why NCS is smoothest.

Author make a obscure definition to make the completeness in mathematical. Remind the space $S[a,b]$ we defined before, now we turn to a new definition $S_2[a,b]$.
It is the space of functions that are 1. differnetiable on [a,b] 2. "have absolutely continuous first derivative. That is, g is continuous and differentiable everywhere on [a,b] with derivative g', and there is an integrable function $g''$ such that $\int _a ^xg''(t)dt=g'(x)-g'(a)$ for all x in [a,b]".(Full quote P16 paragraph 3).

$S_2[a,b]$ contains $S[a,b]$, then g is smoothest in $S_2[a,b]$.

Theorem 2.3

$\widetilde g \in S_2[a,b]$ is an intepolating for $(t_i,z_i)$. g is NCS.
Then $\int \widetilde g''^2 \geq g''^2$, equality hold only if $\widetilde g$ and $g$ are identical.

Proof:

Define $h\in S_2[a,b]$ by $h=\widetilde g-g$.
$$
\begin{aligned}
\int _a^b\widetilde g''^2 &=\int_a^b(g''+h'')^2=\int _a^b g''^2+2g''h''+h''^2\\
\end{aligned}
$$
Then we need deal with the interact term.
We have
$$
\begin{align}
\int _a ^b g''(t)h''(t)dt&=-\int _a ^b g'''(t)h'(t)dt\\
&=-\sum _{j=1}^{n-1} g'''(t^+_j)\int _{t_{j}}^{t_{j+1}}h'(t)dt\\
&=-\sum _{j=1}^{n-1} g'''(t_j^+)\{h(t_{j+1})-h(t_j)\}=0
\end{align}
$$
Then the interact term is 0. We have
$$
\begin{aligned}
\int _a^b\widetilde g''^2 &=\int_a^bg''^2+\int _a^bh''^2\geq \int _a ^b g''^2\\
\end{aligned}
$$
QED.


Advantage of NCS: neatly expressed and intuitively attractive minimization, can be calculated in linear time and stored easily as a piecewise polynomial. Not limited by the knots choosen and spline structure itself.


#### 2.3 Smoothing Spline
Notation: $a<t_1<...<t_n<b$ is the knots we defined before, with the observation $Y_1,...,Y_n$.
Assuming $n\geq 3$ to make sure condition in previous theorem are not meaningless. Because when $n=2,1$, then the smoothing line is meaningless, the best curve is just the line cross these two points.
Reminder the form of roughness penalty with the least square loss function as
$$
S(g)=\sum _{i=1}^n \{ Y_i-g(t) \}^2+\alpha \int _a ^b {g''(x)}^2 dx
$$
Our goal is 
$$
\hat g = argmin_{g\ in\ S_2[a,b]} S(g)
$$

##### 2.3.1 Restricting the class of function to be considered

- g is neccessarily a natural cubic spline with knots at the points $t_i$.
  - Suppose g is any function but not a NCS, $\overline g$ is NCS interpolant to the values $g(t_1)$, then $\overline g(t_i)=g(t_i)$. Then we have $\sum \{Y_i-\overline g(t_i)\}^2=\sum \{Y_i-g(t_i)\}^2$. Then the first term of $S(g)$ is the same. By the previous theorem, we have $\int \overline g''^2<\int g'' ^2$, since $\alpha > 0$, then $S(\overline g)< S(g)$. This means Unless g is a natural cubic spline, we can find a smoother NCS to cross the same points as g but less roughness penalty. Then our task from search all the function in $S_2[a,b]$ becomes only a finite set, only search a natural cubic spline with knots $t_i$.$$S_2[a,b]\rightarrow NCS[a,b]$$. Then the problem becomes to found a NCS, or more specificly, find the coefficients of the cubic spline.
  
##### 2.3.2 Existence & Uniqueness of the minimizing spline curve.

- Suppose g is a NCS with $g,\gamma,Q,R$ (Definition in first theorem).
- Represent $S(g)$ by $g,\gamma,Q,R$ in order to minimizer g existance and unique.
  1. $\sum\{ Y_i-g(t_i) \}^2=(Y-g)^T(Y-g)$
  2. Roughness penalty: $\int g''=g^TKg$ (By first theorem).
$$
\begin{align}
S(g)&=(Y-g)^T(Y-g)+\alpha g^TKg\\
&=g^T(I+\alpha K)g-2Y^Tg+Y^TY
\end{align}
$$

$\alpha K$ is Non-negative definite.

$I+\alpha K$ is Strictly positive definite.

Then back to the $S(g)=g^T(I+\alpha K)g-2Y^Tg+Y^TY$, a quadratic form with the positive definite matrix. Then unique minimum by setting $g=(I+\alpha K)^{-1} Y$. Because we can rewrite the quadratic form as $\{\mathbf{g}-(I+\alpha K)^{-1}\mathbf{Y}\}^T(I+\alpha K)\{\mathbf{g}-(I+\alpha K)^{-1}\}+c(Y)$. Then this is a quadratic form is always strictly positive except $\mathbf{g}$ satisfies $(1+\alpha K)^{-1}\mathbf{Y}$, when it is zero.

> Comment:
> The condition for uniqueness and existenc  of the solve of quadratic form???? More mathmatics maybe?

By the second theorem, once got $\mathbf{g}$, it defines the spline g uniquely.

Theorem 2.4 Suppose $n\geq 3$, and knots $t_1,...,t_n$ are knots with $a<t_1<...<t_n<b.$ Observations $Y_1,...,Y_n$ and a strictly positive smoothing parameter $\alpha$.$\hat g$ be the Natural cubic spline with knots at $t_1,...,t_n$ defined by $\mathbf{g}=(I+\alpha K)^{-1}\mathbf{Y}$. Then for any given g in $S_2[a,b]$,
$$
S(\hat g)\geq S(g)
$$
with equality only if g and $\hat g$ are identical.

Using the result upon, we can deduce a algorithm to calculate the cubic smoothing spline.

##### The Reinsch algorithm

Overall strategy: Set up a non-singular linear system for $\gamma_i$ of $\hat g$ at knots $t_i$. The matrix of the linear system is banded matrix, then can be solved with O(n). From $K=QR^{-1}Q^T$ and $g=(I+\alpha K)^{-1} Y$, we have
$$
\begin{align}
(I+\alpha QR^{-1}Q^T)\mathbf{g}&=Y\\
\mathbf{g}&=Y-\alpha QR^{-1}Q^T\mathbf{g}
\end{align}
$$
Also by theorem2.1, $Q^T\mathbf{g}=R\gamma$
$$
\begin{align}
\mathbf{g}=Y-\alpha Q\gamma\\
(R+\alpha Q^TQ)\gamma=Q^TY
\end{align}
$$
$R+\alpha Q^TQ$ is a bandmatrix with bandwidth 5, it is also symmetric and strictly positive-definite. Solve this can get $\gamma$.
In order to make it sufficiency, it has a Cholesky decomposition of the form
$$
R+\alpha Q^TQ=LDL^T
$$
D is a strictly positive diagonal matrix, L is a lower triangular band matrix with $L_{ij}=0$ for $j<i-2$ and $j>i$, and $L_{ii}=1$ for all i. Q,R are band matrices, can be found in O(n) algebraic operations and only need store the non-zero diagonals. L and D also require linear time for computation.
Then the following is Reinsch algorithm, each step can be performed in O(n) algebraic operations.

##### Algorithm for spline smoothing

- **STEP 1** Evaluate the vector $Q^TY$, by using the formula $(Q^T\mathbf{g})_i=\frac{g_{i+1}-g_{i}}{h_i}-\frac{g_i-g_{i-1}}{h_{i-1}}$
- **STEP 2** Find the non-zero diagonals of $R+\alpha Q^TQ$, then calculate the cholesky decomposition factor L and D.
- **STEP 3** Write $(R+\alpha Q^TQ)\gamma=Q^TY$ and solve this equation for $\gamma$ by forward and back substitution.
- **STEP 4** From (2.14), use 
$$
\mathbf{g}=Y-\alpha Q\gamma
$$
to find $\mathbf{g}$.

 **STEP 1** need only performed once for each data set and not need repeat if new value $\alpha$ is used.(In the circumstance that using AIC, BIC.... method to find the best $\alpha$). If new data value $Y$ are used, Step 1 need to repeat but step 2 only involve design matrix X, not need to be repeated.
 
> Comment:
> All of these results and based on the construction in theorem 1, the form of Q and R. Not only the minimize property, but also the existence, uniqueness, and the calculation methods. But why construction like that is mysterious for me right now. Even the next part proves the theorem, but the proof is based on the structure of Q and R, rather than how to get Q and R, so still unknown.






 
